name: Build and Deploy React App

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy to CentOS
        uses: brian-kiplagat/portfolio@main
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: whoami
