name: Build and Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

  deploy:
    runs-on: self-hosted

    needs: build

    steps:
      - name: Deploy to CentOS 7
        run: |
          echo "Starting deployment..."
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /usr/share/nginx/portfolio && rm -rf * && exit"
          scp -o StrictHostKeyChecking=no -P ${{ secrets.SSH_PORT }} -r build/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/usr/share/nginx/portfolio/
          echo "Deployment completed."
